In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('datasets.csv')
df.shape

(61, 6)

In [30]:
df.dtypes

datasetName      object
about            object
link             object
categoryName     object
cloud            object
vintage         float64
dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   datasetName   61 non-null     object
 1   about         61 non-null     object
 2   link          61 non-null     object
 3   categoryName  61 non-null     object
 4   cloud         24 non-null     object
 5   vintage       31 non-null     float64
dtypes: float64(1), object(5)
memory usage: 3.0+ KB

In [34]:
df = df.drop(['datasetName'], axis=1)
df.head()

,about,link,categoryName,cloud,year
0,American Gut (Microbiome Project),https://github.com/biocore/American-Gut,Biology,GitHub,NaN
1,Global Biotic Interactions (GloBI),https://github.com/jhpoelen/eol-globi-data/wik...,Biology,GitHub,NaN
2,Global Climate Data Since 1929,http://en.tutiempo.net/climate,Climate/Weather,NaN,1929.0
3,3.5B Web Pages from CommonCraw 2012,http://www.bigdatanews.com/profiles/blogs/big-...,Computer Networks,NaN,2012.0
4,53.5B Web clicks of 100K users in Indiana Univ.,http://cnets.indiana.edu/groups/nan/webtraffic...,Computer Networks,NaN,NaN

In [ ]:
df.describe()
# interquartile range -> 25%, 50%, 75% (25% to 75% is the interquartile range)

           vintage
count    31.000000
mean   2000.677419
std      24.436840
min    1920.000000
25%    2006.500000
50%    2009.000000
75%    2012.000000
max    2016.000000

In [36]:
df=df.rename(columns={'vintage':'year'})
df.head()

,about,link,categoryName,cloud,year
0,American Gut (Microbiome Project),https://github.com/biocore/American-Gut,Biology,GitHub,NaN
1,Global Biotic Interactions (GloBI),https://github.com/jhpoelen/eol-globi-data/wik...,Biology,GitHub,NaN
2,Global Climate Data Since 1929,http://en.tutiempo.net/climate,Climate/Weather,NaN,1929.0
3,3.5B Web Pages from CommonCraw 2012,http://www.bigdatanews.com/profiles/blogs/big-...,Computer Networks,NaN,2012.0
4,53.5B Web clicks of 100K users in Indiana Univ.,http://cnets.indiana.edu/groups/nan/webtraffic...,Computer Networks,NaN,NaN

In [38]:
df.shape

(61, 5)

In [46]:
duplicates = df.duplicated()
print("Number of duplicate rows: ", duplicates.shape)

Number of duplicate rows:  (61,)

In [47]:
print(df.isnull().sum())

about            0
link             0
categoryName     0
cloud           37
year            30
dtype: int64

In [52]:
df.dropna()
df

,about,link,categoryName,cloud,year
32,FBI Hate Crime 2013 - aggregated data,https://github.com/emorisse/FBI-Hate-Crime-Sta...,Social Sciences,GitHub,2013.0
41,NYC Uber trip data April 2014 to September 2014,https://github.com/fivethirtyeight/uber-tlc-fo...,Transportation,GitHub,2014.0